version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: unicorn-bank-postgres
    environment:
      POSTGRES_USER: unicorn
      POSTGRES_PASSWORD: unicorn
      POSTGRES_DB: unicorn_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
